//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompressPicture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_UserBuildingCircle
    {
        public string TalkId { get; set; }
        public Nullable<int> TalkType { get; set; }
        public string TalkTitle { get; set; }
        public string TalkContent { get; set; }
        public int TalkView { get; set; }
        public int IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string IpAddress { get; set; }
        public string IpLocal { get; set; }
        public string FirstTitleImg { get; set; }
        public string DisplayPrivacyId { get; set; }
        public string ResourceObj { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> collections { get; set; }
        public Nullable<int> commentss { get; set; }
        public Nullable<int> ShareCount { get; set; }
    }
}
