//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompressPicture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_ItemLibrary
    {
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Views { get; set; }
        public string Description { get; set; }
        public Nullable<int> DownloadsNumber { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
        public int IsDelete { get; set; }
        public string Remarks { get; set; }
        public string ItemContent { get; set; }
        public string ItemTitleImg { get; set; }
        public string ItemFilePath { get; set; }
        public string ItemFileName { get; set; }
        public string ItemContentBefore { get; set; }
        public int IsAdmin { get; set; }
        public int WebUserItemIsOk { get; set; }
        public string ItemAnotherName { get; set; }
        public Nullable<int> IsOriginal { get; set; }
    }
}
